
server:
  #定义本程序启动时监听的端口
  port: 8080

spring:
  datasource:
    #使用HikariData高效连接池
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.42:3306/scf_front_dev?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: scf_front
    password: 123456
    platform: mysql
    initializationMode: NEVER
    continue-on-error: true
  freemarker:
      request-context-attribute: request  #req访问request
#      suffix: .html  #后缀名
      content-type: text/html
      enabled: true
      cache: false #缓存配置
#      template-loader-path: classpath:/templates/ #模板加载路径 按需配置
      charset: UTF-8 #编码格式
      settings:
        number_format: '0.##'   #数字格式化，无小数点
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.bytter.scf.**.entity
  typeEnumsPackage: com.bytter.scf.**.entity.enums
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
#    序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
#    key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
#    #自定义sql注入器,不在推荐使用此方式进行配置,请使用自定义bean注入
#    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
#    #自定义填充策略接口实现,不在推荐使用此方式进行配置,请使用自定义bean注入
#    meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
    # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
    sql-parser-cache: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
#logging
logging:
  file: ./logs/bytter.log
  level:
    root: warn
